# Generated by Django 4.2.6 on 2023-11-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_review_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='papa_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.comment'),
        ),
    ]
